AdaptiveLearning/Controllers/PracticeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using AdaptiveLearning.Models.MathQuizViewModels;
using AdaptiveLearning.Models;
using AdaptiveLearning.Helpers;
using AdaptiveLearning.Data;



namespace AdaptiveLearning.Controllers
{
    [Authorize]
    public class PracticeController : Controller
    {
        private MathQuizDbContext context;

        public PracticeController(MathQuizDbContext dbContext)
        {
            context = dbContext;
        }


        public IActionResult Index()
        {
            return View();
        }

    }  
}

AdaptiveLearning/Views/Practice/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<div class="card" style="width: 20rem;">    
    <div class="card-block">
        <h4 class="card-title">Math Facts</h4>
        <p class="card-text">Practice your math facts.</p>
    </div>
    <ul class="list-group list-group-flush">
        <a href="MathQuiz/Random"><li class="list-group-item">Generate random problems</li></a>
        <a href="MathQuiz"><li class="list-group-item">Retake test your taking previously</li></a>        
    </ul>
    
</div>

AdaptiveLearning/Views/Practice/MathRandomDisplay.cshtml
 
@model MathQuizModel

@{
    ViewData["Title"] = "MathRandomDisplay";
}


<div class="row">
        
    <div class="col-md-12 text-center divination" id="math-quiz">
        $${}$$      
        <input type="text" name="answer" id="math-quiz-line-3" />
    </div>    
    
</div>


@section scripts{
<script type="text/javascript">
    $(function () {


        var mathQuizParams =
            {
                number1LowRange: @Model.Number1LowRange,
                number1HighRange: @Model.Number1HighRange,
                number2LowRange: @Model.Number2LowRange,
                number2HighRange: @Model.Number2HighRange,
                operations: [],
                numQuestions: @Model.NumQuestions,
            };
        @foreach (var op in Model.Operations)
        {
            @:mathQuizParams.operations.push("@op.ToString()");
        }
        

        var getRandom = function (min, max)
        {
            min = Math.ceil(min);
            max = Math.floor(max);
            return Math.floor(Math.random() * (max - min + 1)) + min;
        };

        var mathQuizResultJsonData = {
            quiz: { questions: "", created: (new Date()).toISOString() },
            result: {points: "", secsperquestion: ""}     
        }; 

        var generateQuestion = function () {
            var num1 = getRandom(mathQuizParams.number1LowRange, mathQuizParams.number1HighRange);
            var num2 = getRandom(mathQuizParams.number2LowRange, mathQuizParams.number2HighRange);
            var operator = mathQuizParams.operations[getRandom(0, mathQuizParams.operations.length - 1)];

            // Make sure the biggest number is on top
            if (num2 > num1) {
                var temp = num2;
                num2 = num1;
                num1 = temp;
            }

            return { num1: num1, num2: num2, operator: operator };
         };

        var loadQuestion = function () {
            var question = generateQuestion();    
                        
            
            var mathExpression = "\\begin{array}{r}&" + question.num1 + "\\\\" + question.operator + "\\!\\!\\!\\!\\!\\!&" + question.num2 + "\\\\\\hline\\end{array}";
            mathExpression = mathExpression.replace("&#x2B;", "+");
                                                           

            MathJax.Hub.Queue(function () {
                var math = MathJax.Hub.getAllJax("math-quiz")[0];
                //console.log("Mathjax", math);
                MathJax.Hub.Queue(["Text", math, mathExpression]); }
            );
            var math = document.getElementById("#math-quiz");
            
            return question;
        };

        // &#x2B; is html encoded representation of the '+' symbol
        var operatorFuncArr = {
            '&#x2B;': function(a, b) {
                return a + b;
            },
            'x': function(a, b) {
                return a * b;
            },
            '-': function (a, b) {
                return a - b;
            },
            '/': function (a, b) {
                return a / b;
             }
        };

        var question = loadQuestion();
        var startTime = Date.now();
        var endTime;

        const Emotion = {            
            Contempt: 'Contempt',
            Disgust: 'Disgust',
            Fear: 'Fear',
            Happiness: 'Happiness',
            Neutral: 'Neutral',
            Sadness: 'Sadness',
            Surprise: 'Surprise'
        }
                
        

        $("#math-quiz-line-3").on('keyup', function (e) {
            if (e.keyCode == 13) { // enter key
                endTime = Date.now();
                
                var correct_answer = operatorFuncArr[question.operator](question.num1, question.num2);
                //console.log("Answer is:", correct_answer);
                
                if (correct_answer == event.target.value) {
                    // 1 in the arr represents a correct answer
                    mathQuizResultJsonData.result.points += (1).toString() + " ";
                }
                else{
                        mathQuizResultJsonData.result.points += (0).toString() + " ";
                    }

                mathQuizResultJsonData.quiz.questions += question.num1 + question.operator + question.num2 + " ";
                mathQuizResultJsonData.result.secsperquestion += ((endTime - startTime) / 1000).toString() + " ";

                    if ((mathQuizResultJsonData.result.points.split(" ").length - 1) == mathQuizParams.numQuestions) {

                        $.ajax({
                            url: "/Practice/PostJson",
                            type: "POST",                            
                            data: mathQuizResultJsonData,
                            success: function (data) {
                                if (data.state == 0) {
                                    document.location="/Practice/PostJson";
                                    
                                }                                
                            }
                        });

                    }
                    else {
                        // Reset text box and load next question
                        $('#math-quiz-line-3').val('');
                        question = loadQuestion();
                        startTime = Date.now();
                    }
                
               
                
            }
            console.log(mathQuizResultJsonData);
        });

    });
</script>

 }       

AdaptiveLearning/Views/Practice/MathRandomSelect.cshtml
@model AdaptiveLearning.Models.MathQuizViewModels.MathQuizRandomViewModel

@{
    ViewData["Title"] = "MathRandom";
}

<h2>MathRandom</h2>
<form asp-controller="Practice" 
      asp-action="MathRandomDisplay"
      method="post">

    
    <div class="form-group">
        <p>
            <label asp-for="Number1">Number One Range:</label>
            <input class="form-control" asp-for="Number1" type="text" id="number1" readonly style="border:0; color:#f6931f; font-weight:bold;">
        </p>
        <div id="slider-range-1"></div>            
    </div>
    <div class="form-group">
        <p>
            <label asp-for="Number2">Number Two Range:</label>
            <input class="form-control" asp-for="Number2" type="text" id="number2" readonly style="border:0; color:#f6931f; font-weight:bold;">
        </p>
        <div id="slider-range-2"></div>
    </div>
    <div class="form-group">
            <fieldset>
            <label>Operations:</label>
            <label asp-for="Operations" style="color:#f6931f">Addition</label>
            <input class="form-control"  type="checkbox" name="Operations" id="checkbox-1" value="\+" />
                &nbsp;
            <label asp-for="Operations" style="color:#f6931f">Subtraction</label>
            <input class="form-control"  type="checkbox" name="Operations" id="checkbox-2" value="-"/>
                &nbsp;
            <label asp-for="Operations" style="color:#f6931f">Multiplication</label>
            <input class="form-control"  type="checkbox" name="Operations" id="checkbox-3" value="x"/>
                &nbsp;
            <!--<label asp-for="Operations" style="color:#f6931f">Division</label>
            <input class="form-control"  type="checkbox" name="Operations" id="checkbox-4" value="/"/> -->
        </fieldset> 
                
               
    </div>
    <div class="form-group">
        <label asp-for="NumQuestions">Number of Problems</label>
        <input class="form-control" asp-for="NumQuestions" type="text" name="NumQuestions" id="problemCount" />
    </div>
            
       
     
    
    <input type="submit"  value="Create Practice Test" />
</form>