AdaptiveLearning/Controllers/MathQuizController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AdaptiveLearning.Models.MathQuizViewModels;
using AdaptiveLearning.Models;
using AdaptiveLearning.Data;
using AdaptiveLearning.Helpers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace AdaptiveLearning.Controllers
{
    [Authorize]
    public class MathQuizController : Controller
    {

        private MathQuizDbContext context;

        public MathQuizController(MathQuizDbContext dbContext)
        {
            context = dbContext;
        }

        // GET: SavedMathQuizs
        public async Task<IActionResult> Index()
        {
            return View(await context.SavedMathQuizzes.ToListAsync());
        }

        

        // GET: SavedMathQuizs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: SavedMathQuizs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,questions,created,UserID")] SavedMathQuiz savedMathQuiz)
        {
            if (ModelState.IsValid)
            {
                context.Add(savedMathQuiz);
                await context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(savedMathQuiz);
        }

        
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var savedMathQuiz = await context.SavedMathQuizzes.SingleOrDefaultAsync(m => m.ID == id);
            if (savedMathQuiz == null)
            {
                return NotFound();
            }
            return View(savedMathQuiz);
        }

        public async Task<IActionResult> MathRetakeDisplay(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var savedMathQuiz = await context.SavedMathQuizzes.SingleOrDefaultAsync(m => m.ID == id);
            if (savedMathQuiz == null)
            {
                return NotFound();
            }
            return View(savedMathQuiz);
        }

        // POST: SavedMathQuizs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,questions,created,UserID")] SavedMathQuiz savedMathQuiz)
        {
            if (id != savedMathQuiz.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    context.Update(savedMathQuiz);
                    await context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SavedMathQuizExists(savedMathQuiz.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(savedMathQuiz);
        }

        // GET: SavedMathQuizs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var savedMathQuiz = await context.SavedMathQuizzes
                .SingleOrDefaultAsync(m => m.ID == id);
            if (savedMathQuiz == null)
            {
                return NotFound();
            }

            return View(savedMathQuiz);
        }

        // POST: SavedMathQuizs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var savedMathQuiz = await context.SavedMathQuizzes.SingleOrDefaultAsync(m => m.ID == id);
            context.SavedMathQuizzes.Remove(savedMathQuiz);
            await context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool SavedMathQuizExists(int id)
        {
            return context.SavedMathQuizzes.Any(e => e.ID == id);
        }

        [Route("MathQuiz/Random")]
        [HttpGet]
        public IActionResult MathRandomSelect()
        {
            return View();
        }



        [HttpPost]
        public IActionResult MathRandomDisplay(MathQuizRandomViewModel mathQuizRandomViewModel)
        {
            MathQuizModel mathQuizModel = new MathQuizModel();

            var number1 = mathQuizRandomViewModel.Number1.Split(' ');

            mathQuizModel.Number1LowRange = int.Parse(number1[0]);
            mathQuizModel.Number1HighRange = int.Parse(number1[1]);

            var number2 = mathQuizRandomViewModel.Number2.Split(' ');
            mathQuizModel.Number2LowRange = int.Parse(number2[0]);
            mathQuizModel.Number2HighRange = int.Parse(number2[1]);

            mathQuizModel.Operations = mathQuizRandomViewModel.Operations;

            mathQuizModel.NumQuestions = mathQuizRandomViewModel.NumQuestions;



            return View(mathQuizModel);

        }


        private static QuizResultBundle _datas;

        [HttpPost]
        public JsonResult PostJson(QuizResultBundle data)
        {

            if (data != null && ModelState.IsValid)
            {

                _datas = data;
                SavedMathQuiz quiz = _datas.quiz;
                ResultMathQuiz result = _datas.result;

                // Add data to the models on the c# side
                quiz.UserID = User.getUserId();

                // Save quiz to db
                context.SavedMathQuizzes.Add(quiz);
                context.SaveChanges();

                int quizId = quiz.ID;


                // Add quiz id to result and save to db
                result.SavedMathQuizID = quizId;
                context.ResultMathQuizzes.Add(result);
                context.SaveChanges();

            }

            return Json(new
            {
                state = 0,
                msg = string.Empty
            });

        }


        [HttpPost]
        public JsonResult PostJsonResult(ResultMathQuiz result)
        {

            if (result != null && ModelState.IsValid)
            {                                   
                
                // Add quiz id to result and save to db                
                context.ResultMathQuizzes.Add(result);
                context.SaveChanges();

            }

            return Json(new
            {
                state = 1,
                msg = string.Empty
            });

        }

        [HttpGet]
        public IActionResult PostJson()
        {
            return View(_datas);

        }

        
        // GET: SavedMathQuizs/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            
            using (context)
            {
                var quiz = context.SavedMathQuizzes
                    .Single(q => q.ID == id);

                var results = context.Entry(quiz)
                    .Collection(q => q.Results)
                    .Query()
                    .Where(r => r.SavedMathQuizID == id)
                    .ToList();

                quiz.Results = results;

                if (quiz == null)
                {
                    return NotFound();
                }

               return View(quiz);
            }
                        
        }
    }
}

AdaptiveLearning/Views/MathQuiz/Details.cshtml
@model AdaptiveLearning.Models.SavedMathQuiz

@{
    ViewData["Title"] = "Details";

}

<h2>Details</h2>

<div>
    <h4>SavedMathQuiz</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.questions)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.questions)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.created)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.created)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UserID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UserID)
        </dd>
    </dl>
</div>

<div>
    <canvas id="myChart"></canvas> 
 <!--@*   <ul>

            @foreach (var result in Model.Results) {
             <li>
               <p>@result.points @result.secsperquestion @result.created</p>

             </li>
             }

    </ul> *@-->



</div>

<div>
    <!-- <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> | -->
    
    <a asp-action="Index">Back to List</a>
</div>


@section scripts{
    <script type="text/javascript">

        var datasets = [];
        var opacity = 1.0;
        var secsPerQuestion = [];
        var savedFirstResult = [];
        var index = 0;

        var count = 0;

        @{var isFirstResult = true;}


        @foreach (var op in Model.Results) {

            foreach (var secs in op.secsperquestion.Split(' '))
            {

                        @:secsPerQuestion.push("@secs.ToString()");


            }
            @*
            if (isFirstResult)
            {
                @:savedFirstResult = secsPerQuestion.slice();
                isFirstResult = false;
            }
            else
            {
               
                @:secsPerQuestion.forEach(function (currentValue, index) { secsPerQuestion[index] = (parseFloat(secsPerQuestion[index]) - parseFloat(savedFirstResult[index]) > 0 ? parseFloat(secsPerQuestion[index]) - parseFloat(savedFirstResult[index]) : parseFloat(savedFirstResult[index]) + (parseFloat(secsPerQuestion[index]) - parseFloat(savedFirstResult[index])) ).toString(); }); 
        }*@

            <text>

            datasets.push({
                label: "@Convert.ToString(op.created)",
                data: secsPerQuestion,
                backgroundColor: "rgba(55, 160, 225," + opacity + ")",
                hoverBackgroundColor: "rgba(155,160,225,0.7)",
                hoverBorderWidth: 2,
                HoverBorderColor: 'lightgrey'

            });
            secsPerQuestion = [];
            opacity -= 0.2;
            </text>


        }
        console.log("DATASETS", datasets);
        Charts.StackedResultBarChart(datasets);
        //Charts.StackedResultLineChart(datasets);


    </script>

}

AdaptiveLearning/Views/MathQuiz/Index.cshtml
@model IEnumerable<AdaptiveLearning.Models.SavedMathQuiz>

    @{
    ViewData["Title"] = "Index";
    
    }

    <h2>Index</h2>

    <p>
        <a asp-action="Create">Create New</a>
    </p>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.questions)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.created)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.UserID)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model) {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.questions)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.created)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UserID)
                    </td>
                    <td>
                        <a asp-action="MathRetakeDisplay" asp-route-id="@item.ID">Retake</a> |
                        <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                    </td>
                </tr>
}
        </tbody>
    </table>

AdaptiveLearning/Views/MathQuiz/MathRandomDisplay.cshtml
 
@model MathQuizModel

@{
    ViewData["Title"] = "MathRandomDisplay";
}


<div class="row">
        
    <div class="col-md-12 text-center divination" id="math-quiz">
        $${}$$      
        <input type="text" name="answer" id="math-quiz-line-3" />
    </div>    
    
</div>

@section scripts{
<script type="text/javascript">
   var mathQuizParams =
            {
                number1LowRange: @Model.Number1LowRange,
                number1HighRange: @Model.Number1HighRange,
                number2LowRange: @Model.Number2LowRange,
                number2HighRange: @Model.Number2HighRange,
                operations: [],
                numQuestions: @Model.NumQuestions,
            };
   @foreach (var op in Model.Operations)
            {
                @:mathQuizParams.operations.push("@op.ToString()");
            }
             

   MathQuizModule(mathQuizParams);
    </script>

}

AdaptiveLearning/Views/MathQuiz/MathRandomSelect.cshtml
@model AdaptiveLearning.Models.MathQuizViewModels.MathQuizRandomViewModel

@{
    ViewData["Title"] = "MathRandom";
}

<h2>MathRandom</h2>
<form asp-controller="MathQuiz" 
      asp-action="MathRandomDisplay"
      method="post">

    
    <div class="form-group">
        <p>
            <label asp-for="Number1">Number One Range:</label>
            <input class="form-control" asp-for="Number1" type="text" id="number1" readonly style="border:0; color:#f6931f; font-weight:bold;">
        </p>
        <div id="slider-range-1"></div>            
    </div>
    <div class="form-group">
        <p>
            <label asp-for="Number2">Number Two Range:</label>
            <input class="form-control" asp-for="Number2" type="text" id="number2" readonly style="border:0; color:#f6931f; font-weight:bold;">
        </p>
        <div id="slider-range-2"></div>
    </div>
    <div class="form-group">
            <fieldset>
            <label>Operations:</label>
            <label asp-for="Operations" style="color:#f6931f">Addition</label>
            <input class="form-control"  type="checkbox" name="Operations" id="checkbox-1" value="\+" />
                &nbsp;
            <label asp-for="Operations" style="color:#f6931f">Subtraction</label>
            <input class="form-control"  type="checkbox" name="Operations" id="checkbox-2" value="-"/>
                &nbsp;
            <label asp-for="Operations" style="color:#f6931f">Multiplication</label>
            <input class="form-control"  type="checkbox" name="Operations" id="checkbox-3" value="x"/>
                &nbsp;
            <!--<label asp-for="Operations" style="color:#f6931f">Division</label>
            <input class="form-control"  type="checkbox" name="Operations" id="checkbox-4" value="/"/> -->
        </fieldset> 
                
               
    </div>
    <div class="form-group">
        <label asp-for="NumQuestions">Number of Problems</label>
        <input class="form-control" asp-for="NumQuestions" type="text" name="NumQuestions" id="problemCount" />
    </div>
            
       
     
    
    <input type="submit"  value="Create Practice Test" />
</form>

AdaptiveLearning/Views/MathQuiz/MathRetakeDisplay.cshtml
@model SavedMathQuiz

@{
    ViewData["Title"] = "MathRetakeDisplay";
}


<div class="row">

    <div class="col-md-12 text-center divination" id="math-quiz">
        $${}$$
        <input type="text" name="answer" id="math-quiz-line-3" />
    </div>

</div>

@section scripts{
    <script type="text/javascript">
   

  MathQuizModule(null, "@Model.questions", @Model.ID);
       
    </script>

}

AdaptiveLearning/Views/MathQuiz/PostJson.cshtml
@using AdaptiveLearning.Models;

@model QuizResultBundle


<h2>Quiz Data</h2>
<p>@Model.quiz.ID</p>
<p>@Model.quiz.questions</p>
<p>@Model.quiz.created</p>
<p>@Model.quiz.UserID</p>
<p>@Model.quiz.Results</p>

<h2>Result Data</h2>
<p>@Model.result.points</p>
<p>@Model.result.secsperquestion</p>
<p>@Model.result.EmotionalStatePerQuestion</p>
<p>@Model.result.SavedMathQuizID</p>





    

AdaptiveLearning/Views/MathQuiz/QuizResult.cshtml
@model String


  
        <p>
            <span>@Model</span>
        
        </p>
    
    